// Code generated by wit-bindgen-go. DO NOT EDIT.

package calc

// This file contains wasmimport and wasmexport declarations for "example:calculator".

//go:wasmexport example:calculator/calc#add
//export example:calculator/calc#add
func wasmexport_Add(a0 uint32, b0 uint32) (result0 uint32) {
	a := (int32)((uint32)(a0))
	b := (int32)((uint32)(b0))
	result := Exports.Add(a, b)
	result0 = (uint32)(result)
	return
}
